#!/bin/bash

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  🌐 CONFIGURE www.islakayd.com FOR YOUR PROJECT            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Check which platform is being used
echo -e "${BLUE}📋 Checking deployment platform...${NC}"
echo ""

if [ -f "vercel.json" ]; then
    PLATFORM="Vercel"
    echo -e "${GREEN}✓ Detected: Vercel${NC}"
elif [ -f "netlify.toml" ]; then
    PLATFORM="Netlify"
    echo -e "${GREEN}✓ Detected: Netlify${NC}"
else
    PLATFORM="Unknown"
    echo -e "${RED}✗ No deployment platform detected${NC}"
fi

echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""

if [ "$PLATFORM" = "Vercel" ]; then
    echo -e "${YELLOW}📝 VERCEL DOMAIN SETUP STEPS:${NC}"
    echo ""
    echo "1️⃣  Go to Vercel Domains Settings:"
    echo "   ${BLUE}https://vercel.com/dashboard${NC}"
    echo "   → Click on your 'islakaydpro' project"
    echo "   → Go to 'Settings' → 'Domains'"
    echo ""
    echo "2️⃣  Add Custom Domain:"
    echo "   • Click 'Add' button"
    echo "   • Enter: ${GREEN}www.islakayd.com${NC}"
    echo "   • Click 'Add'"
    echo ""
    echo "3️⃣  Also add (for redirect):"
    echo "   • Enter: ${GREEN}islakayd.com${NC}"
    echo "   • Click 'Add'"
    echo ""
    echo "4️⃣  Configure DNS (Choose ONE method):"
    echo ""
    echo "   ${YELLOW}METHOD A - Vercel Nameservers (Easiest):${NC}"
    echo "   • Vercel will show nameservers like:"
    echo "     ns1.vercel-dns.com"
    echo "     ns2.vercel-dns.com"
    echo "   • Go to your domain registrar (GoDaddy/Namecheap/etc)"
    echo "   • Find 'Nameservers' or 'DNS Settings'"
    echo "   • Replace with Vercel's nameservers"
    echo "   • Save (takes 10-60 minutes)"
    echo ""
    echo "   ${YELLOW}METHOD B - Custom DNS Records:${NC}"
    echo "   • Add these records at your domain registrar:"
    echo ""
    echo "     ${GREEN}For www.islakayd.com:${NC}"
    echo "     Type: CNAME"
    echo "     Name: www"
    echo "     Value: cname.vercel-dns.com"
    echo ""
    echo "     ${GREEN}For islakayd.com (root):${NC}"
    echo "     Type: A"
    echo "     Name: @"
    echo "     Value: 76.76.21.21"
    echo ""
    echo "5️⃣  Wait for DNS Propagation:"
    echo "   • Usually 10-60 minutes"
    echo "   • Check status: ${BLUE}https://www.whatsmydns.net/#A/www.islakayd.com${NC}"
    echo ""
    echo "6️⃣  Verify:"
    echo "   • Visit: ${GREEN}https://www.islakayd.com${NC}"
    echo "   • SSL will auto-configure (takes 1-2 minutes)"
    echo ""

elif [ "$PLATFORM" = "Netlify" ]; then
    echo -e "${YELLOW}📝 NETLIFY DOMAIN SETUP STEPS:${NC}"
    echo ""
    echo "1️⃣  Go to Netlify Domain Settings:"
    echo "   ${BLUE}https://app.netlify.com${NC}"
    echo "   → Click on your site"
    echo "   → Go to 'Domain management'"
    echo ""
    echo "2️⃣  Add Custom Domain:"
    echo "   • Click 'Add custom domain'"
    echo "   • Enter: ${GREEN}www.islakayd.com${NC}"
    echo "   • Click 'Verify'"
    echo "   • Click 'Add domain'"
    echo ""
    echo "3️⃣  Configure DNS (Choose ONE method):"
    echo ""
    echo "   ${YELLOW}METHOD A - Netlify DNS (Easiest):${NC}"
    echo "   • Click 'Set up Netlify DNS'"
    echo "   • Netlify will show nameservers"
    echo "   • Go to your domain registrar"
    echo "   • Replace nameservers with Netlify's"
    echo "   • Save (takes 10-60 minutes)"
    echo ""
    echo "   ${YELLOW}METHOD B - External DNS:${NC}"
    echo "   • Add this record at your domain registrar:"
    echo ""
    echo "     ${GREEN}For www.islakayd.com:${NC}"
    echo "     Type: CNAME"
    echo "     Name: www"
    echo "     Value: [your-site-name].netlify.app"
    echo ""
    echo "4️⃣  Enable HTTPS:"
    echo "   • Netlify auto-provisions SSL"
    echo "   • Takes 1-2 minutes after DNS propagates"
    echo ""
    echo "5️⃣  Verify:"
    echo "   • Visit: ${GREEN}https://www.islakayd.com${NC}"
    echo ""
fi

echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo -e "${GREEN}📌 QUICK REFERENCE:${NC}"
echo ""
echo "Domain to configure: ${GREEN}www.islakayd.com${NC}"
echo "Project: islakaydpro"
echo "Platform: $PLATFORM"
echo ""
echo -e "${YELLOW}💡 TIPS:${NC}"
echo "• DNS changes can take 10-60 minutes"
echo "• SSL certificates auto-provision after DNS is set"
echo "• Use METHOD A (Nameservers) for easiest setup"
echo "• Use METHOD B if you need to keep other DNS records"
echo ""
echo -e "${BLUE}🔍 Check DNS Propagation:${NC}"
echo "https://www.whatsmydns.net/#CNAME/www.islakayd.com"
echo ""
echo -e "${GREEN}✅ Once configured, your site will be live at:${NC}"
echo "https://www.islakayd.com"
echo ""
