#!/bin/bash

# 🚀 VERCEL DEPLOYMENT STEPS FOR ISLAKAYD.COM

echo "╔════════════════════════════════════════════════════════╗"
echo "║  🚀 DEPLOYING ISLAKAYD TO VERCEL                      ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}📋 STEP 1: Login to Vercel${NC}"
echo "Run this command and follow the prompts:"
echo ""
echo -e "${GREEN}  vercel login${NC}"
echo ""
echo "Choose one of these login methods:"
echo "  • Continue with GitHub (recommended)"
echo "  • Continue with Email"
echo ""
read -p "Press ENTER when you've logged in..."
echo ""

echo -e "${BLUE}📋 STEP 2: Deploy to Vercel${NC}"
echo "Run this command to deploy:"
echo ""
echo -e "${GREEN}  vercel --prod${NC}"
echo ""
echo "Vercel will ask you questions. Answer like this:"
echo ""
echo "? Set up and deploy \"~/islakaydpro\"? [Y/n]"
echo "  → Press ENTER (Yes)"
echo ""
echo "? Which scope do you want to deploy to?"
echo "  → Choose your account"
echo ""
echo "? Link to existing project? [y/N]"
echo "  → Press N (No - new project)"
echo ""
echo "? What's your project's name?"
echo "  → Type: islakayd (or press ENTER)"
echo ""
echo "? In which directory is your code located?"
echo "  → Press ENTER (./ is correct)"
echo ""
echo "? Want to override the settings? [y/N]"
echo "  → Press N (No)"
echo ""
read -p "Press ENTER to continue with deployment..."
echo ""

echo -e "${YELLOW}⏳ Deploying... This will take 1-2 minutes...${NC}"
echo ""

# Show what's happening
echo "Vercel will:"
echo "  ✓ Upload your code"
echo "  ✓ Build your project"
echo "  ✓ Deploy to production"
echo "  ✓ Give you a URL like: https://islakayd-xxx.vercel.app"
echo ""

echo -e "${GREEN}════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${BLUE}📋 STEP 3: Add Custom Domain (After Deployment)${NC}"
echo ""
echo "1. Go to: https://vercel.com/dashboard"
echo ""
echo "2. Click on your 'islakayd' project"
echo ""
echo "3. Go to: Settings → Domains"
echo ""
echo "4. Click 'Add Domain'"
echo ""
echo "5. Enter: islakayd.com"
echo ""
echo "6. Click 'Add'"
echo ""
echo "7. Also add: www.islakayd.com"
echo ""

echo -e "${BLUE}📋 STEP 4: Configure DNS Records${NC}"
echo ""
echo "Go to your domain registrar (GoDaddy, Namecheap, etc.)"
echo "Add these DNS records:"
echo ""
echo -e "${YELLOW}For Root Domain (islakayd.com):${NC}"
echo "  Type: A"
echo "  Name: @ (or leave blank)"
echo "  Value: 76.76.21.21"
echo "  TTL: Auto or 3600"
echo ""
echo -e "${YELLOW}For WWW Subdomain:${NC}"
echo "  Type: CNAME"
echo "  Name: www"
echo "  Value: cname.vercel-dns.com"
echo "  TTL: Auto or 3600"
echo ""

echo -e "${GREEN}════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${BLUE}📋 STEP 5: Wait for DNS Propagation${NC}"
echo ""
echo "DNS changes take 5-60 minutes to propagate."
echo "Check status at: https://dnschecker.org/"
echo ""

echo -e "${GREEN}════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${GREEN}✅ ALL DONE!${NC}"
echo ""
echo "Your app will be available at:"
echo "  🌐 https://islakayd.com"
echo "  🌐 https://www.islakayd.com"
echo ""
echo "📱 Users can install it on:"
echo "  • iOS (Safari → Share → Add to Home Screen)"
echo "  • Android (Chrome → Menu → Install app)"
echo "  • Desktop (Install icon in browser)"
echo ""
echo -e "${YELLOW}🎉 Congratulations! Your app is live! 🎉${NC}"
echo ""
