#!/bin/bash
# Simple script to create user and seed data

echo "🚀 ISLAKAYD - Quick Setup Script"
echo "================================"
echo ""
echo "The 'Database error saving new user' happens because Supabase"
echo "requires proper auth setup with database triggers."
echo ""
echo "🎯 SOLUTION (Takes 30 seconds):"
echo ""
echo "1. Open this link in your browser:"
echo "   https://supabase.com/dashboard/project/ialxlykysbqyiejepzkx/auth/users"
echo ""
echo "2. Click the green 'Add User' button"
echo ""
echo "3. Fill in the form:"
echo "   ┌─────────────────────────────────┐"
echo "   │ Email: demo@islakayd.com        │"
echo "   │ Password: Demo123456!           │"
echo "   │ ☑ Auto Confirm User (CHECK THIS)│"
echo "   └─────────────────────────────────┘"
echo ""
echo "4. Click 'Create User'"
echo ""
echo "5. Wait 2 seconds for the profile to be created"
echo ""
echo "6. Then run this:"
echo "   npm run seed:equipment"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 What happens next:"
echo "   ✅ Script finds your new user"
echo "   ✅ Creates 15 professional equipment listings"
echo "   ✅ Assigns them to your account"
echo "   ✅ Your marketplace is instantly populated!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🌐 Alternative - Create via your website:"
echo "   Visit: http://localhost:5173"
echo "   Click: 'Get Started' → Sign up"
echo "   Then run: npm run seed:equipment"
echo ""
